EOD_API_KEY = " 67f85e26e8e254.34037967"

START_YEAR = 2005
END_YEAR = 2024
START_MONTH = 1
END_MONTH = 1   
START_DAY = 1
END_DAY = 1

QUESTDB_URI = "postgresql://admin:quest@amudhan-nuc.boa-vibes.ts.net:8812/qdb"

EXCHANGE = "US"
TICKERS = ['FCX', 'JEF', 'EXPE', 'FOXA', 'AGCO', 'AIZ', 'MUSA', 'BK', 'UGI', 'NSIT', 'BALL', 'BJ', 'HES', 'ORI', 'CL', 'EMN', 'LAD', 'OMC', 'PCG', 'YUMC', 'NYCB', 'RF', 'BGST', 'HPE', 'AVY', 'WSO', 'UNP', 'LEA', 'VST', 'STLD', 'GPN', 'MTZ', 'CPB', 'ABG', 'LRCX', 'EQH', 'QRTEA', 'GT', 'FANG', 'LYV', 'ODP', 'APA', 'CMS', 'CNXC', 'CTVA', 'EOG', 'ZTS', 'MU', 'RSG', 'NWSA', 'THO', 'D', 'HBAN', 'MAN', 'ADP', 'NSC', 'ALK', 'PH', 'WAB', 'CBRE', 'AAP', 'IP', 'LDOS', 'CDW', 'LUV', 'RPM', 'EL', 'BDX', 'RUSHB', 'EA', 'CLX', 'SWK', 'LVS', 'ICE', 'ZBH', 'DXC', 'OXY', 'PVH', 'KMX', 'AA', 'ADBE', 'ARW', 'RS', 'INGR', 'AMAT', 'FITB', 'TMHC', 'HIG', 'CTSH', 'PPL', 'MGM', 'SO', 'OC', 'IFF', 'CCK', 'JWN', 'GPI', 'ATUS', 'CMI', 'DRI', 'IBKR', 'GILD', 'KHC', 'ITW', 'NEE', 'BAX', 'UHS', 'IEP', 'AFG', 'TAP', 'DINO', 'DUK', 'AMP', 'BAH', 'W', 'IPG', 'UFPI', 'BECN', 'CARR', 'MTB', 'BWA', 'BSX', 'BLK', 'KLAC', 'THC', 'NWL', 'PYPL', 'ORLY', 'SAH', 'GNW', 'BBWI', 'MAS', 'CVNA', 'BURL', 'SATS', 'CAR', 'AEP', 'SKX', 'FLR', 'PFG', 'INTU', 'TXT', 'CHK', 'PWR', 'ED', 'MMC', 'CHWY', 'GPC', 'RGA', 'CASY', 'R', 'CTAS', 'BIIB', 'TFC', 'KMB', 'PPG', 'GIS', 'REGN', 'PII', 'NOV', 'EBAY', 'VFC', 'APD', 'LSXMA', 'KEY', 'CHRW', 'ABM', 'PAG', 'DD', 'BLDR', 'FL', 'SANM', 'MO', 'RJF', 'BKR', 'ACM', 'BKNG', 'HSIC', 'WSM', 'KSS', 'ETR', 'NRG', 'EMR', 'LNG', 'MNST', 'SYK', 'JBHT', 'AMGN', 'DASH', 'AMRK', 'HII', 'BX', 'DHR', 'VTRS', 'SJM', 'CSX', 'SAIC', 'ROK', 'J', 'DGX', 'NVR', 'DLTR', 'DVA', 'MHK', 'TXN', 'NOW', 'FIS', 'OMI', 'LPLA', 'HLT', 'OVV', 'URI', 'ARKO', 'ANDE', 'OSK', 'FCNCA', 'DFS', 'WMB', 'L', 'MAR', 'GPK', 'AMD', 'DK', 'O', 'LULU', 'MSI', 'GXO', 'V', 'NFLX', 'PNC', 'ARMK', 'XEL', 'NGL', 'EIX', 'OKE', 'STZ', 'TOL', 'PARR', 'CEG', 'AVT', 'HSY', 'SMCI', 'CAG', 'GWW', 'BERY', 'MA', 'VOYA', 'FNF', 'MCD', 'JLL', 'LUMN', 'UNFI', 'JBLU', 'KKR', 'CMC', 'GLW', 'ULTA', 'OTIS', 'GLP', 'PHM', 'ALV', 'EXC', 'PARA', 'AMT', 'PEG', 'LH', 'APH', 'XPO', 'SPGI', 'TSCO', 'ALLY', 'ON', 'AZO', 'VMC', 'CINF', 'LKQ', 'KNX', 'DOV', 'X', 'SQ', 'FI', 'ABNB', 'WRK', 'LHX', 'DKS', 'WEC', 'CPNG', 'NTRS', 'ES', 'KDP', 'GPS', 'WCC', 'XYL', 'IQV', 'VRTX', 'AN', 'SPTN', 'MCHP', 'ALB', 'MKL', 'STT', 'K', 'ISRG', 'M', 'HAL', 'TRGP', 'SEB', 'CLF', 'APO', 'DTE', 'WDC', 'CZR', 'HRL', 'LNC', 'KMI', 'UNM', 'MMM', 'ECL', 'AFL', 'SRE', 'WY', 'EQIX', 'SHW', 'SCHW', 'CNP', 'WDAY', 'RADCQ', 'WLK', 'ADI', 'FE', 'WM', 'MOS', 'SYF', 'AJG', 'BEN', 'ROST', 'EME', 'DVN', 'EXPD', 'HTZ', 'WRB', 'GEHC', 'WHR', 'KD', 'CFG', 'CE', 'PKG', 'CMG', 'FAST', 'AEE', 'CYH', 'NEM', 'DAN', 'PLD', 'AES']